#!/usr/bin/env bash
# Configure NGINX so that its HTTP response contains a custom header.
var=$(hostname)
nstr="error_page 404\/custom_404.html;\n location \/redirect_me{\n return 301 \$scheme:\/\/www.google.com;"
nstr2="server {\n\tadd_header X-Served-By $var;"


apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sef -i -E "s/^[^#]+location \/ \{/$nstr/" /etc/nginx/sites_available/default
sudo sed -i -E "s/^server \{/$nstr2/" /etc/nginx/sites_available/default
sudo service nginx start
