#!/usr/bin/env bash
# Installs and configures HAproxy in a load balancer server.

sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 100.25.211.234:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
