#!/usr/bin/env bash
# Creates a file 'myscript.pid' containing its PID.
# It displays 'To infinity and beyond' indefinitely.
# Displays 'I hate the kill command' when receinving a SIGTERM signal.
# it also displays ' Y U no love me?!' when receiving a SIFINT signal.
# and deletes the file 'myscript.pid' and terminates itself.

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit 0' SIGTERM
	trap 'sudo rm -f /var/run/myscript.pid; exit 0' SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
done
