#!/usr/bin/env bash
# Prints 'To infinity and beyond' indefinitely,
# and 'I am invincible!!!' when receinving a SIGTERM.

trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
