#!/usr/bin/env bash
# It displays numbers from 1 to 100 in a list format.
# FizzBuzz when the number is a multiple of 3 and 5.
# Fizz when the number is a multiple of 3.
# Buzz when the number is a multiple of 5.
# Otherwise displays the number.

for x in {1..100}
do
	if [[ $((x % 5)) = 0 && $((x % 3)) = 0 ]]
	then
		echo "FizzBuzz"
	elif [ $((x % 5)) = 0 ]
	then
		echo "Buzz"
	elif [ $((x % 3)) = 0 ]
	then
		echo "Fizz"
	else
		echo $x
	fi
done
