#!/usr/bin/env bash
# It displays "Best School" in a 10 times loop, with the exceptions of:
# 4th iteration displays "bad luck".
# 8th iteration displays "good luck".

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 3 ]
	then
		echo "bad luck"
	elif [ $c -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( c++ ))
done
