#!/usr/bin/env bash
# It displays numbers from 1 to 20, with the exception of:
# "bad luck from China" on the 4th iteration.
# "bad luck from Japan" on the 9th iteration.
# "bad luck from Italy" in the 17th iteration.

c=1

while [ $c -le 20 ]
do
	echo "$c"
	case $c in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((c++))
done
